//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRoleRekenModule.ServRefRekenModule32 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServRefRekenModule32.IRekenModule32")]
    public interface IRekenModule32 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRekenModule32/Calculate32", ReplyAction="http://tempuri.org/IRekenModule32/Calculate32Response")]
        int Calculate32();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRekenModule32/Calculate32Mutex", ReplyAction="http://tempuri.org/IRekenModule32/Calculate32MutexResponse")]
        int Calculate32Mutex();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRekenModule32Channel : WebRoleRekenModule.ServRefRekenModule32.IRekenModule32, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RekenModule32Client : System.ServiceModel.ClientBase<WebRoleRekenModule.ServRefRekenModule32.IRekenModule32>, WebRoleRekenModule.ServRefRekenModule32.IRekenModule32 {
        
        public RekenModule32Client() {
        }
        
        public RekenModule32Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RekenModule32Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RekenModule32Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RekenModule32Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Calculate32() {
            return base.Channel.Calculate32();
        }
        
        public int Calculate32Mutex() {
            return base.Channel.Calculate32Mutex();
        }
    }
}
